# -*- coding: utf-8 -*-
"""kitap_onerisi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19rzflerKPNCK5zMKyZGHiyddhGrO-atO
"""

yas = int(input("Yasınızı giriniz: "))

if yas <= 12:
  print("Çocuk kitapları önerilir.")

elif 13 <= yas <= 17:
  print("Gençlik kitapları önerilir.")

elif yas >= 18:
  print("Klasik eserler önerilir.")