# -*- coding: utf-8 -*-
"""not_hesaplama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YpR4AAYW69-6aal5aaAahXkYK0wmkiCJ
"""

#HARF NOTU ÖĞRENME

notu = int(input("Notunuzu giriniz:"))

if notu >= 90:
  print("AA")

elif notu >= 85:
  print("BA")

elif notu >= 75:
  print("BB")

elif notu >= 65:
  print("CB")

elif notu >= 55:
  print("CC")

elif notu <= 50:
  print("FF")