# -*- coding: utf-8 -*-
"""sinema_kampanyasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eGNYVR2UX3XFPv-Na7E039Y2kpFyipAQ
"""

#sinema bilet indirimi

yas = int(input("Yasınızı giriniz: "))

if yas <= 18 or yas >= 65:
  print("İndirim kazandınız!")

else:
  print("Normal bilet ücreti.")

#sinema kampanyasi

yas = int(input("Kaç yasındasınız? "))

ögrenci = (input("Ögrenci misiniz? "))

if yas <= 18 and ögrenci == "evet":
  print("İndirim kazandınız!")

else:
  print("İndirim kazanamadınız!")