# -*- coding: utf-8 -*-
"""02_yas_kontrol.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBztA3hFbkVQWduInkWdkpFHjar7gD_F
"""

yaş = int(input("Yaşınızı giriniz: "))

if yaş >= 18:
  print("Reşitsiniz!")