# -*- coding: utf-8 -*-
"""sayilar1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZJePaMdGdHE31oBZwTFzUvOIYfYqGEHM
"""

#sayilar

sayi1 = int(input("Bir sayi giriniz: "))

sayi2 = int(input("Bir sayi giriniz: "))

if sayi1 > sayi2:
  print("1. sayi büyüktür.")

if sayi2 > sayi1:
  print("2. sayi büyüktür.")

if sayi1 == sayi2:
  print("Sayilar eşittir.")