# -*- coding: utf-8 -*-
"""sayilar2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LjfEJvM54q1isDO_RciKDYoGRe5gDMdJ
"""

#sayilar2

sayi1 = int(input("Bir sayi giriniz: "))

sayi2 = int(input("Bir sayi giriniz: "))

sayi3 = int(input("Bir sayi giriniz: "))

if sayi1 >= sayi2 and sayi1 >= sayi3:
  print("En büyük sayi: ", sayi1)

elif sayi2 >= sayi1 and sayi2 >= sayi3:
  print("En büyük sayi: ", sayi2)

else:
  print("En büyük sayi: ", sayi3)