# -*- coding: utf-8 -*-
"""07_sayi_tahmin_oyunu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cu_SoM0XjZqTXFnMhbUunFD_p_Iqy52r
"""

# Sayı Tahmin Oyunu 🎲
# Python öğrenirken yaptığım mini proje.
# while döngüsünü henüz öğrenmediğim için oyun şu an tek tahminlik çalışıyor.
# while öğrendikten sonra tamamlayacağım.

import random

sayi = random.randint(1, 50)

tahmin = int(input("Bir sayi tahmin et: "))

if sayi < tahmin:
  print("Daha büyük bir sayi tahmin et!")

  tahmin = int(input("Tekrar tahmin et: "))

elif sayi > tahmin:
  print("Daha küçük bir sayi tahmin et!")

  tahmin = int(input("Tekrar tahmin et: "))

if sayi == tahmin:
  print("Doğru bildin!")